services:
  - type: web
    name: prince-portfolio
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false