services:
  - type: web
    name: prince-portfolio
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000